/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.a544jh.kanamemory.ui.typinggame;

import com.a544jh.kanamemory.gamelogic.TypingGame;
import com.a544jh.kanamemory.ui.GamePanel;
import java.awt.CardLayout;

/**
 *
 * @author axel
 */
public class TypingGamePanel extends javax.swing.JPanel implements GamePanel {

    private TypingGame game;
    private final String COMPONENT_NAME;

    /**
     * Creates new form TypingGamePanel
     */
    public TypingGamePanel() {
        COMPONENT_NAME = "TypingGame";
        initComponents();
        inputField.setText("");
        hintLabel.setText("");
    }

    public void setGame(TypingGame game) {
        this.game = game;
        refresh();
    }

    public void refresh() {
        kanaLabel.setText(game.getCurrentCharacter().charcterString());
        hintLabel.setText(game.getHint());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        kanaLabelPanel = new javax.swing.JPanel();
        kanaLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        hintLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 600));

        backButton.setText("Main Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        kanaLabelPanel.setBackground(new java.awt.Color(255, 255, 255));
        kanaLabelPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        kanaLabel.setFont(new java.awt.Font("Dialog", 1, 200)); // NOI18N
        kanaLabel.setText("あ");

        javax.swing.GroupLayout kanaLabelPanelLayout = new javax.swing.GroupLayout(kanaLabelPanel);
        kanaLabelPanel.setLayout(kanaLabelPanelLayout);
        kanaLabelPanelLayout.setHorizontalGroup(
            kanaLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kanaLabel)
        );
        kanaLabelPanelLayout.setVerticalGroup(
            kanaLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kanaLabel)
        );

        inputField.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        inputField.setText("aaa");
        inputField.setMinimumSize(new java.awt.Dimension(100, 61));
        inputField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                inputFieldComponentShown(evt);
            }
        });
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        hintLabel.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        hintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintLabel.setText("Hint: --");
        hintLabel.setPreferredSize(new java.awt.Dimension(476, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(kanaLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kanaLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout cl = (CardLayout) getParent().getLayout();
        cl.previous(getParent());
        getParent().remove(this);
    }//GEN-LAST:event_backButtonActionPerformed

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        game.makeMatch(inputField.getText());
        inputField.setText("");
        refresh();
    }//GEN-LAST:event_inputFieldActionPerformed

    private void inputFieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_inputFieldComponentShown

    }//GEN-LAST:event_inputFieldComponentShown

    public String getComponentName() {
        return COMPONENT_NAME;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel kanaLabel;
    private javax.swing.JPanel kanaLabelPanel;
    // End of variables declaration//GEN-END:variables
}
